sudo: required
services:
  - docker
before_install:
  - docker build -t rassumpcao/rajavascript -f Dockerfile.dev .
script:
  - docker run rassumpcao/rajavascript npm test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "ragnarok"
  env: "Ragnarok-env"
  bucket_name: "elasticbeanstalk-sa-east-1-718945484108"
  bucket_path: "ragnarok"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"